//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notes_Market_Place.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class SellerNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SellerNote()
        {
            this.Downloads = new HashSet<Download>();
            this.SellerNotesAttechments = new HashSet<SellerNotesAttechment>();
            this.SellerNotesReportedIssues = new HashSet<SellerNotesReportedIssue>();
            this.SellerNotesReviews = new HashSet<SellerNotesReview>();
        }
    
        public int ID { get; set; }
        public int SellerID { get; set; }
        public int Status { get; set; }



        public Nullable<int> ActionBy { get; set; }
        public string AdminRemarks { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        [Required(ErrorMessage = "This is Required Field")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Please Select the Category")]
        public int Category { get; set; }

        public string DisplayPicture { get; set; }

        public HttpPostedFileBase DisplayImage { get; set; }

        [Required(ErrorMessage = "Please Select the file.")]
        public HttpPostedFileBase[] uploadNote { get; set; }

        public Nullable<int> NoteType { get; set; }
        public Nullable<int> NumberofPages { get; set; }

        [Required(ErrorMessage = "Description is Required Field")]
        public string Description { get; set; }

        public Nullable<int> Country { get; set; }
        public string University { get; set; }
        public string Course { get; set; }
        public string CourseCode { get; set; }
        public string Professor { get; set; }

        [Required(ErrorMessage = "Please Select the any One Mode")]
        public bool IsPaid { get; set; }

        public Nullable<decimal> SellingPrice { get; set; }

        public string NotesPreview { get; set; }

        public HttpPostedFileBase notepreview { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yyyy}")]
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> MidifiedBy { get; set; }
        public bool IsActive { get; set; }

        public IEnumerable<NotesDetail> notereview { get; set; }

        public virtual Country Country1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Download> Downloads { get; set; }
        public virtual NoteCategory NoteCategory { get; set; }
        public virtual NoteType NoteType1 { get; set; }
        public virtual ReferenceData ReferenceData { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellerNotesAttechment> SellerNotesAttechments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellerNotesReportedIssue> SellerNotesReportedIssues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellerNotesReview> SellerNotesReviews { get; set; }
    }
}
